harnesslabs/arbiter

app/src/tokens/mod.rs

Did Issue #22 
- Added steth and reth
- Made some small formatting changes (whitespace between tokens inits in `tokens/mod.rs`)
Ran arbiter locally on the new tokens and found that pools w/ ETH existed for both.
[RETH ETH Pool on Etherscan](https://etherscan.io/token/0xae78736cd615f374d3085123a210448e74fc6393#tokenTrade)
[STETH ETH Pool on Uniswap analytics](https://info.uniswap.org/#/pools/0xeacdf56d530a4ec6639c2c86f1915f4956446b5c)
Interestingly the only activity on the STETH ETH pool were two deposits and withdrawals  one for 200k and another for 2k (looks like [most of the STETH liquidity is on Curve](https://curve.fi/#/ethereum/pools/steth/deposit))

PR for Issue #22. Adding steth and reth to arbiter.

---

crates/cli/src/config.toml
crates/cli/src/config/mod.rs
crates/cli/src/main.rs

Adds `sim` subcommand for generating gbm instead of it running every time arbiter cli is invoked

Add `sim` subcommand for GBM

---

crates/clairvoyance/src/clairerror.rs
crates/clairvoyance/src/lib.rs
crates/clairvoyance/src/uniswap.rs
crates/cli/src/main.rs

- In response to #71 
- Created an enum for `ClairvoyanceError` in a new file `../src/clairerrors.rs`
- Wrote logic for `Display` for the different error types (`TokenDoesNotExist, FeeTierDoesNotExist, PoolDoesNotExist`)
- Replaced `.unwrap()` with custom flow wherever possible with the appropriate errors when an error is necessary
- We should probably add custom errors for other cases outside of command line inputs (also didn't get around to handling config files)

#71 Added Error Handling when command line input is invalid

---

crates/cli/src/main.rs

Currently running `arbiter` with no subcommand provides no helpful information, this PR prints out the help log for `arbiter` when no subcommand is provided

Print help if no subcommand supplied 🐱

---

crates/simulate/src/agent.rs
crates/simulate/src/environment.rs
crates/simulate/src/lib.rs

Event logging will be important for agents to act upon. So, what I tried to do here was implement a buffer called `event_buffer` that the `SimulationEnvironment` owns (as an attribute) write access to and, upon execution, echoes out logs into this buffer. Other agents can freely read at any time. Due to this write protection, the buffer is not mutex. We can get away with `Arc<RwLock<...>>`.
I'm not sure this is the best way to handle it, but it seems to work well for now! Some other changes came along with this. 
To see this in action, just investigate `test_event_logging` in Simulation's lib.

Implemented an event buffer

---

crates/cli/src/config.toml
crates/simulate/src/price_simulation.rs

fixed the GBM process in price_simulation.rs and changed the config to match units of time between sigma timestep and mu. Closes #163

Fixed GBM in price_simulation.rs

---

README.md

I have added a slight modification to the `install.sh` to use the rust bin directory that is already created and added to the path automatically on Windows.
Closes #234

Fixes issue #234

---

.github/workflows/bump_version.yml
README.md
crates/bindings/Cargo.toml
crates/cli/Cargo.toml
crates/on-chain/Cargo.toml
crates/simulate/Cargo.toml

Debugging versioning

---

documentation/book.toml
documentation/src/SUMMARY.md
documentation/src/chapter_1.md
documentation/src/chapter_2.md
documentation/src/chapter_3.md

Begin Mdbook-based documentation. Resolves #169 
* Add a section for the `portfolio` subdirectory of ```/bin/simulations/```
* Improve [mdBook](https://github.com/rust-lang/mdBook) formatting

Documentation: Initialize and Outline a Mdbook

---

bin/visualize/mod.rs

A recent change to `visualization-rs` changed the argument count for `transparent_plot()`. This breaks the build/check for arbiter. Adding `None` as the missing argument allows you to build and use the program.

Fixed build error

---

arbiter-core/src/environment.rs
arbiter-core/src/middleware.rs
arbiter-core/src/tests/bindings.rs
arbiter-core/src/tests/contracts.rs
arbiter-core/src/tests/interaction.rs
arbiter-core/src/tests/mod.rs

Test cleanup

---

arbiter-core/Cargo.toml
arbiter-core/src/environment.rs
arbiter-core/src/manager.rs
arbiter-core/src/middleware.rs

cleanup custom error types

---

arbiter-core/src/environment.rs
arbiter-core/src/manager.rs
arbiter-core/src/middleware.rs
arbiter-core/src/tests/contracts.rs
arbiter-core/src/tests/interaction.rs
arbiter-core/src/tests/management.rs
arbiter-core/src/tests/mod.rs
arbiter-core/src/tests/signer.rs

Introduced a new struct EnvironmentParameters to streamline the process of initializing environments in the Manager. This refactoring effort encapsulates block_rate and seed parameters within the new struct, making the code more readable and scalable for future additions.
Closes #449

feat: Add `EnvironmentParameters` struct for improved environment initialization

---

README.md
bin/init.rs

This pull request implements the changes requested in issue #428 by changing the `init` command to also redo the contract bindings.

bind on init

---

arbiter-core/Cargo.toml

The last PR #449 make some changes to end user API, we neglected to bump the minor version to indicate this.

chore: bump minor version

---

arbiter-core/Cargo.toml
arbiter-core/src/environment.rs
arbiter-core/src/lib.rs
arbiter-core/src/manager.rs
arbiter-core/src/middleware.rs
arbiter-core/src/tests/management.rs

This PR provides a quick fix to the `Manager::stop_environment()` method by replacing `tx_receiver.recv()` with `tx_receiver.try_recv()`. 
Closes #456 
---
Please merge after #458

fix: environment stop

---

arbiter-core/benches/bench.rs
arbiter-core/src/environment.rs
arbiter-core/src/manager.rs
arbiter-core/src/middleware.rs
arbiter-core/src/tests/contracts.rs
arbiter-core/src/tests/interaction.rs
arbiter-core/src/tests/management.rs
arbiter-core/src/tests/mod.rs
arbiter-core/src/tests/signer.rs

Added derives for `EnvironmentParams` so that they may be read in via toml and handled more easily. We now have:
```rust
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EnvironmentParameters
```
Furthermore, placed the label in the `EnvironmentParameters` struct.
Closes #470 and closes #471

feat: derives for `EnvironmentParameters` and move label

---

arbiter-core/Cargo.toml

Updated `RustQuant` import so that we can take advantage of the "seedable" feature flag for seeding stochastic processes.
Closes #474

feat: version change for `RustQuant` with "seedable" feature

---

arbiter-core/src/environment.rs
arbiter-core/src/middleware.rs

- Cleaned up the `EnvironmentError`s and their handling as well. 
- Removed some unnecessary structs by repackaging into Rust's `Result` enum.
- Took those changes and made necessary changes to `middleware.rs` to handle this more succinctly.
Closes #477

chore: improve environment errors

---

arbiter-core/benches/bench.rs
arbiter-core/src/bindings/block_info.rs
arbiter-core/src/bindings/mod.rs
arbiter-core/src/environment.rs
arbiter-core/src/manager.rs
arbiter-core/src/math.rs
arbiter-core/src/middleware.rs
arbiter-core/src/tests/contracts.rs
arbiter-core/src/tests/interaction.rs
arbiter-core/src/tests/management.rs
arbiter-core/src/tests/mod.rs
arbiter-core/src/tests/signer.rs
contracts/BlockInfo.sol

Provides an upgraded API for handling block updates with added user control, i.e.:
Provides an ability to procedurally update block timestamps when using `BlockType::RandomlySampled`. Furthermore, gives the ability to update block timestamps via the `update_block` function as well.
Furthermore, there is a refactor of the comms used in `RevmMiddleware` to `Environment` which feels much cleaner to me.
Closes #418 and closes #464
**NOTE THAT THIS SHOULD COME AFTER #478 AS IT IS FORKED FROM THAT HEAD**

feat: block type enum

---

arbiter-core/Cargo.toml
arbiter-core/src/bindings/arbiter_math.rs
arbiter-core/src/bindings/arbiter_token.rs
arbiter-core/src/bindings/liquid_exchange.rs

Places the `serde::Serialize` and `serde:Deserialize` traits on all structs/enums in Arbiter's native contract bindings.
Closes #503

feat(contracts): contract serde derives

---

arbiter-derive/Cargo.toml

This changes the manifest for our proc-macros to be published to crates.io

manifest for publishing derive

---

.github/workflows/test.yaml
README.md
arbiter-core/src/tests/middleware_instructions.rs

Closes #498 by running tests with rust version 1.71

bug fix: use rustc version 1.71 rather than latest stable version for tests

---

arbiter-core/Cargo.toml
arbiter-core/src/middleware.rs
arbiter-core/src/tests/middleware_instructions.rs
arbiter-core/src/tests/mod.rs

Replace the `recv()` with `try_recv()` in the `FilterWatcher` implementation in `RevmMiddleware`. This creates a non-blocking future. As a bonus, this allows for a timeout in the filter watcher tests so we can remove the odd way we checked it now.
Closes #521

fix(#521): filterwatcher `recv`

---

README.md
vulnerability_corpus.md

Closes #526 
Still need to be able to reproduce the bug, working on this here: https://github.com/primitivefinance/portfolio_simulations/pull/39

vulnerability corpus

---

Cargo.toml
bin/bind.rs

Closes #465 
This PR filters out bindings for any interface, test, or other ancillary contracts while ensuring the shared types are still generated. 
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request updates the version of the "arbiter" package to 0.3.4 and adds a new dependency "tempfile" with version 3.8.0 to the dev-dependencies section in the Cargo.toml file. It also modifies the code to use only one codegen unit, collect a list of contracts from a specific directory, remove unnecessary contracts, and generate bindings for submodules.
> 
> ## What changed
> - Updated the version of the "arbiter" package to 0.3.4 in the Cargo.toml file.
> - Added a new dependency "tempfile" with …

Feat bind for chosen contracts

---

arbiter-core/Cargo.toml
arbiter-core/benches/bench.rs
arbiter-core/src/environment/builder.rs
arbiter-core/src/environment/mod.rs
arbiter-core/src/environment/tests.rs
arbiter-core/src/middleware/mod.rs
arbiter-core/src/tests/clients.rs
arbiter-core/src/tests/middleware_instructions.rs
arbiter-core/src/tests/mod.rs

This PR Closes #560 
It also modifies the `RevmMiddleware` Constructor to return an `Arc<RevmMiddleware>` To improve the ease of use a bit since i don't believe there is a time in which we don't do this.
This does also have passing tests, clippy, and fmt

auto run + contructor return arc

---

README.md
docs/src/SUMMARY.md
docs/src/getting_started/cargo_install.md

* Adds docs to setup and install Arbiter CLI, building from source
* README typo fix
Resolves #557

docs: setup and cli installation details

---

.github/workflows/test.yaml

- Runs tests on 3 core macos-latest deployment rather than 2 core ubuntu-latest, see [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners)
edit: running the tests on macos makes data_capture pass

Test workflow on macos-latest

---

bin/bind.rs

closes #628 
This add a bool field to the toml table the we can set to want interfaces. By default it is turned off.

Bind include interfaces

---

bin/bind.rs

With the arbiter config "bindings_workspace", it's taking the workspace as the root directory and adding "src/bindings", then at the end of the function it adds another "/bindings", so output for the workspace "simulation" is "simulation/src/bindings/bindings". 
I remove the first addition of bindings so we rely on the join at the end of the function.

fix(bind): output directory outputs to src/bindings

---

Cargo.lock
arbiter-core/Cargo.toml
arbiter-core/src/data_collection.rs
arbiter-core/src/environment/errors.rs
arbiter-core/src/environment/mod.rs
arbiter-core/src/middleware/mod.rs
arbiter-core/src/tests/data_collection_integration.rs
bin/bind/digest.rs

- Adds missing `break`s to break out of the event collector while loop when data is successfully written to file
- Adds logic for broadcasting a shutdown signal from `data_collection.rs` threads to the main environment thread to guarantee that output data is written to completion

break event collector loop

---

arbiter-core/src/environment/cheatcodes.rs
arbiter-core/src/environment/mod.rs
arbiter-core/src/middleware/mod.rs

This is a draft PR for the issue #606 
It seems like `BlockId` enum is no longer supported in alloy types. https://github.com/primitivefinance/arbiter/blob/c6ea6ab526afc1d9e349a501d2213d2b2d34115f/arbiter-core/src/environment/cheatcodes.rs#L28C9-L28C9
So what should be the approach here? Should I create a enum that wrappes both `BlockHash` and `BlockNumber` or do something else for that?

feat: Change types from ethers types to alloy types in cheatcodes

---

.github/workflows/lint.yaml
.github/workflows/test.yaml
Cargo.lock
arbiter-core/Cargo.toml
arbiter-core/src/environment/cheatcodes.rs
arbiter-core/src/environment/mod.rs
arbiter-core/src/middleware/mod.rs
arbiter-core/src/tests/contracts.rs
arbiter-core/src/tests/mod.rs
bin/fork/tests.rs

We had found that the changes to Alloy primitives caused a handful of breaks in `arbiter-core`. These could not be resolved easily, so they have been reverted for now. This was found simultaneously as we had integration tests hidden behind a missing feature flag. Also also, the `--all` flag was deprecated around the same time in favor of `--workspace` for `cargo test` which caused us grief too. 
Apologies to @quidproquoo for reverting these changes. This is on us.
I have also `#[ignore]`d three tests that have to do with forking. Features here haven't changed, and these tests continuously eat up a lot of time and often break for reasons unknown.

bugfix: revert alloy and fix tests

---

Cargo.lock
Cargo.toml
arbiter-engine/Cargo.toml
arbiter-engine/src/agent.rs
arbiter-engine/src/lib.rs
arbiter-engine/src/world.rs

Started out the new `arbiter-engine` crate with some initial structure.
Closes #733 and closes #734

feat(arbiter-engine): init crate and scaffold agent

---

Cargo.lock
Cargo.toml
arbiter-core/Cargo.toml
arbiter-core/src/middleware/connection.rs
arbiter-core/src/middleware/mod.rs
arbiter-engine/Cargo.toml
arbiter-engine/src/agent.rs
arbiter-engine/src/examples.rs
arbiter-engine/src/lib.rs
arbiter-engine/src/messager.rs
arbiter-engine/src/world.rs

Creates some more abstractions to be used in `arbiter-engine` with some starter examples that don't yet run. Main things are:
- Agent messaging layer.
- Beginning of `World` abstraction.
Closes #738

arbiter-engine: worlds and messaging layer

---

Cargo.lock
Cargo.toml
arbiter-bindings/Cargo.toml
arbiter-core/Cargo.toml
arbiter-core/src/environment/mod.rs
arbiter-core/src/middleware/mod.rs
arbiter-engine/Cargo.toml
arbiter-engine/src/agent.rs
arbiter-engine/src/examples.rs
arbiter-engine/src/lib.rs
arbiter-engine/src/messager.rs
arbiter-engine/src/world.rs

This PR adds the ability to have a world ran via `World::run()`. To show how this works, see `arbiter_engine::examples::tests`, specifically the `base_simulation()` function. This will run a simulation that loads an agent's engine with a messager as both a collector and executor which allows for this agent to receive external stimulus and communicate within this layer (potentially to other agents). Externally, "Start" is sent to the agent which kicks off a loop where the agent repeatedly echoes "Hello, world!" every second. This does not exit gracefully yet, use `ctrl + c`. It is a POC.
Closes #745

feat(arbiter-engine): Run method for agents and messager echo example

---

arbiter-core/src/tests/contracts.rs
arbiter-core/src/tests/mod.rs
arbiter-engine/src/agent.rs
arbiter-engine/src/examples.rs
arbiter-engine/src/world.rs

We wanted to not have the `World` struct have generics that come from the `Engine<E,A>` inside of the `Agent` struct. This PR fixes this by introducing a object-safe trait `Entity` that solely provides the interface to do `Agent::run()`. Minimal change with no breaks to tests. Changed the agent collection in `World` from `Vec<Agent>` to `HashMap<String, Agent>` while I was at it.
Closes #747

enhance(arbiter-engine): remove `<E, A>` generics from `World`

---

arbiter-engine/Cargo.toml
arbiter-engine/src/world.rs

Specifies the binding version to use in the engine to enable publishing release

chore version specification

---

arbiter-core/src/database.rs
arbiter-engine/src/world.rs

Adds a new method of creating a `World` with an existing `Environment`, as well as an `AnvilDump` data structure that can be deserialized from a raw dump file created by the `anvil_dumpState` end point.
Many projects deploy their smart contracts with `forge script`. When preparing an Arbiter simulation, these projects currently have to rewrite certain portions (or all) of their deploy scripts in Rust, which creates a possibility of divergent deployment specifications between the simulation and the live protocol.
To make this process smoother and more secure for teams, we can allow users to retain their current deployment scripts, and for Arbiter to load the initial state of an anvil chain after the deployment script has been ran on it.
Currently, the `EnvironmentBuilder` has the following …

feat(arbiter-core): Add `AnvilDump`

---

arbiter-engine/src/agent.rs
arbiter-engine/src/examples/timed_message.rs
arbiter-engine/src/examples/token_minter.rs
arbiter-engine/src/machine.rs
arbiter-engine/src/messager.rs
arbiter-engine/src/world.rs

This PR adds the ability for the `sync()` stage of a `Behavior` to receive the client and messager from the agent the behavior is attached to. It should then be recommended to users to make these fields optional in their behaviors at some point down the road, but we are not done with this design yet. There could be better ways to address this problem, but I'll take this for now.
Closes #819

refactor(arbiter-engine): agent-behavior flow

---

Cargo.lock
arbiter-engine/Cargo.toml
arbiter-engine/src/agent.rs
arbiter-engine/src/errors.rs
arbiter-engine/src/examples/minter/behaviors/token_admin.rs
arbiter-engine/src/examples/minter/behaviors/token_requester.rs
arbiter-engine/src/examples/minter/mod.rs
arbiter-engine/src/examples/mod.rs
arbiter-engine/src/examples/timed_message/mod.rs
arbiter-engine/src/lib.rs
arbiter-engine/src/machine.rs
arbiter-engine/src/messager.rs
arbiter-engine/src/universe.rs
arbiter-engine/src/world.rs
arbiter-macros/Cargo.toml
documentation/src/usage/arbiter_engine/agents_and_engines.md
documentation/src/usage/arbiter_engine/behaviors.md
documentation/src/usage/arbiter_engine/configuration.md
documentation/src/usage/arbiter_engine/worlds_and_universes.md

Give a clear and high level level overview of the tasks completed in this pull request. 
Closes #851

add `arbiter-engine` error handling

---

Cargo.lock
arbiter-engine/Cargo.toml
arbiter-engine/src/examples/minter/behaviors/mod.rs
arbiter-engine/src/examples/minter/behaviors/token_admin.rs
arbiter-engine/src/examples/minter/behaviors/token_requester.rs
arbiter-engine/src/examples/timed_message/mod.rs
arbiter-engine/src/lib.rs
arbiter-engine/src/machine.rs

Some of the traits and their return types are not easily managed with custom errors, so they are replaced with `anyhow::Result` to make the end user's life easier.

migrate to anyhow::Result

---

arbiter-core/Cargo.toml
arbiter-core/src/data_collection.rs
arbiter-core/src/environment/mod.rs
arbiter-core/src/middleware/connection.rs
arbiter-core/src/middleware/mod.rs
arbiter-core/tests/environment_integration.rs
arbiter-core/tests/middleware_integration.rs

Now we can call `my_contract.events().stream_with_meta()`. Not all fields are populated correctly, and this can be addressed in #824 if we want.
Closes #501

feat(arbiter-core): stream with meta

---

arbiter-engine/src/machine.rs

removes redundant `PhantomData` in `Engine`
was originally used for type parameter `E` but now `event_stream` utilizes `E` so `PhantomData` is redundant

nit: remove `PhantomData`

---

docs/src/usage/arbiter_engine/agents_and_engines.md

should be `::builder` instead of `::new`

docs: incorrect method

---

engine/src/machine.rs
examples/minter/behaviors/token_admin.rs
examples/minter/behaviors/token_requester.rs

Closes #912 
We could likely improve this further, but this was a quick fix that should at least let errors be visible.

feat: `error!` output from behavior
