harnesslabs/arbiter

app/src/tokens/mod.rs

Issue #25 
Just changed wseth to wsteth, where it should be (small change lol)

fixing wseth -> wsteth

---

app/src/tokens/mod.rs

Small fix. Just double check I'm not crazy here.

Change token builder to pub

---

app/src/main.rs
app/src/uniswap/mod.rs
app/src/utils/mod.rs

approach for listening to swap events from multiple uniswap pools

Concurrent join!

---

crates/cli/Cargo.toml
crates/cli/src/config.toml
crates/cli/src/config/mod.rs
crates/cli/src/main.rs

adds the error type + better propegation to config we discussed

custom config error type

---

crates/clairvoyance/src/uniswap.rs
crates/cli/src/main.rs

Price impact features

---

crates/clairvoyance/src/uniswap.rs

naming conventions and conciseness

Colins feedback

---

crates/architect/src/lib.rs
crates/clairvoyance/src/uniswap.rs

sry for misleading branch name

testing macro

---

crates/clairvoyance/src/simulation.rs
crates/clairvoyance/src/uniswap.rs
crates/utils/src/chain_tools.rs
crates/utils/src/tokens.rs

this is a pr adding full rustdoc documentation to all public structs and modules.

add full documentation for `clairvoyance`

---

LICENSE
crates/architect/LICENSE
crates/bindings/LICENSE
crates/clairvoyance/Cargo.toml
crates/clairvoyance/LICENSE
crates/cli/LICENSE
crates/simulate/LICENSE
crates/utils/LICENSE
deny.toml

This closes #82 and updates our cargo-deny CI so that we pass.

0xjepsen patch

---

crates/cli/src/main.rs
crates/simulate/src/testbed.rs

Read contract

---

crates/simulate/src/execution.rs

The execution result contains the newly generated address. Let's just use this.

simplified the deploy function

---

crates/cli/src/main.rs
crates/simulate/src/agent.rs
crates/simulate/src/environment.rs
crates/simulate/src/lib.rs

Just a refactor. Should prevent some foot bullets for people in the future

edits that made environment struct more private

---

crates/cli/Cargo.toml
crates/cli/src/backtest_data.rs
crates/cli/src/config.toml
crates/cli/src/config/mod.rs
crates/cli/src/gbm.rs
crates/cli/src/main.rs
crates/cli/src/ou.rs
crates/simulate/src/lib.rs
crates/simulate/src/stochastic/mod.rs
crates/simulate/src/stochastic/price_process.rs

Closes #209. Not really close to done yet just started the restructure. As of this point I've made a `Distribution` trait with one `sample` method along with a series of other distribution structs that implement the trait (everything from `normal` to `gamma` and `beta`). Also have initialized the process of doing the same thing with different types of price paths and a more generic trait `PriceProcess`. Will update progress here

Stochastic.rs Restructure

---

README.md

I just think this order of badges makes the most sense.

rearranging the badge order

---

crates/cli/src/sim/portfolio_sim.rs

looping through prices

---

.github/dependabot.yml
deny.toml

This will itterate through the different paths where we have `Cargo.toml` Files and update the dependencies in each of them daily. 
Closes #305 
Closes #328 
The deny will fail until this is closed https://github.com/primitivefinance/visualization-rs/issues/21

fix dependancy bot :zap:

---

lib/simulate/README.md

Correct typo readme

---

Cargo.toml
bin/init.rs

Implement quote macro in ```init.rs```

---

Cargo.toml
bin/bind.rs
bin/init.rs

Update init.rs ✨

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Provides us with a template for all pull requests to have.
Closes #444

repo: add a pull request template

---

.github/pull_request_template.md

This now works properly, I'm just removing the additional parts that didn't populate correctly. No more changes needed after this. 
N/A, this was quick.

fix: update pull request template

---

README.md

Edited the README to more adequately reflect what the benchmark accomplished.
Links to and closes #462.

chore: update README benchmark info

---

.github/pull_request_template.md

Edited the pull request template to inform about CI checks and versioning.
Closes #463

chore: include CI and version mentions in pull request template

---

arbiter-core/Cargo.toml

Adds
- Authors
- Descriptions
- Keywords
- license
to the manifest for crates.io

manifest changes for crates.io

---

Cargo.toml
bin/init.rs

This PR close #494 by overwriting the manifest with the new project name

rename package upon project initialization

---

Cargo.toml
bin/bind.rs
bin/init.rs

This PR Closes #439 by additionally iterating through the submodules and generating binding for them. 
Please merge https://github.com/primitivefinance/arbiter/pull/495 first

Arbiter bind

---

Cargo.toml
arbiter-core/Cargo.toml
arbiter-core/src/environment.rs
arbiter-core/src/middleware.rs
arbiter-core/src/tests/derives.rs
arbiter-derive/Cargo.toml

ft: bumped a lot of crates to latest version. initialised `blob_hashes` and `max_fee_per_blob_gas` with default values wherever necessary.
closes #536

ft: fix tomls

---

arbiter-core/src/tests/mod.rs

Closes #604 
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request adds a feature flag for contracts in the arbiter-core tests module.
> 
> ## What changed
> A single line was added to the `arbiter-core/src/tests/mod.rs` file. This line is a feature flag that enables the "contracts" feature.
> 
> ```diff
>  #![allow(missing_docs)]
> +#![cfg(feature = "contracts")]
>  
>  // mod interaction;
>  mod clients;
> ```
> 
> ## How to test
> To test this change, you can run the tests in the `arbiter-core` module with the "contracts" feature enabled. If the tests pass, then the change is working as expected.
> 
> ## Why make this change
> This change was made to allow for conditional compilation of …

feature configuration for the tests module

---

.github/workflows/lint.yaml

adds udeps to workflow

---

arbiter-core/Cargo.toml
arbiter-core/src/middleware/mod.rs
arbiter-core/src/tests/environment_control.rs

Closes #624 
The approach i went with here was change the wallet property of the middleware to be an enum of either wallet or forked.

Eoa forking

---

Cargo.toml
arbiter-core/Cargo.toml
arbiter-core/src/middleware/cast.rs
arbiter-core/src/middleware/connection.rs
arbiter-core/src/middleware/errors.rs
arbiter-core/src/middleware/mod.rs
arbiter-core/src/middleware/nonce_middleware.rs
arbiter-derive/Cargo.toml
bin/bind/mod.rs
bin/fork/mod.rs
bin/init.rs
bin/main.rs

added workspace dependancies for shared dependancies
propagated imports up to consolidate `use` and leverage `super`
Closes #685

workspace dependancies

---

.github/workflows/lint.yaml
.github/workflows/release-plz.yml

Generates our lockfile in CI so our builds always match our tomls
Closes #683

generate lock file to match toml in ci for consistent builds

---

arbiter-core/src/middleware/mod.rs

The added label for the client was not made public! This fixes it.

Make label public

---

.github/workflows/test.yaml
Cargo.toml
bin/bind/digest.rs
bin/bind/mod.rs
bin/bind/tests.rs

Added more tests and documentation to work on this
Closes #707

Arbiter bind/debug

---

arbiter-core/src/environment/cheatcodes.rs
arbiter-core/src/environment/mod.rs
arbiter-core/src/tests/middleware_integration.rs

- Adds the Access Cheatcode, which fetches and returns the `DbAccount` for a given address.

feat(access-cheatcode): fetches the DbAccount of an address

---

arbiter-core/src/math.rs

remove custom conversions

---

arbiter-core/src/middleware/connection.rs
arbiter-core/src/middleware/mod.rs

@Alexangelj is this what you want to try working with?

feat: RevMiddleware: Clone + PubSubClient

---

book.toml

remove preprocessor

---

.rustfmt.toml
arbiter-core/benches/bench.rs
arbiter-core/src/coprocessor.rs
arbiter-core/src/environment/mod.rs
arbiter-core/src/environment/tests.rs
arbiter-core/src/middleware/mod.rs
arbiter-core/src/tests/contracts.rs
arbiter-core/src/tests/environment_integration.rs
arbiter-core/src/tests/middleware_integration.rs
arbiter-core/src/tests/mod.rs
arbiter-engine/src/agent.rs
arbiter-engine/src/examples/timed_message.rs
arbiter-engine/src/examples/token_minter.rs
arbiter-engine/src/world.rs
documentation/src/usage/arbiter_core/environment.md
documentation/src/usage/arbiter_core/middleware.md

closes #827 and brings environment in line with agent builder pattern

Agent Builder

---

.github/workflows/test.yaml
Cargo.lock
Cargo.toml
arbiter-core/Cargo.toml
arbiter-core/benches/bench.rs
arbiter-core/tests/common.rs
arbiter-core/tests/contracts.rs
arbiter-core/tests/data_collection_integration.rs
arbiter-core/tests/environment_integration.rs
arbiter-core/tests/middleware_integration.rs
arbiter-engine/Cargo.toml
arbiter-engine/src/agent.rs
arbiter-engine/src/lib.rs
arbiter-engine/src/machine.rs

Attempts to fix all the failing CI after merging a bunch of stuff.

fix CI issues prior to release

---

Cargo.lock
Cargo.toml
arbiter-core/tests/environment_integration.rs
bin/fork/digest.rs
bin/fork/mod.rs

Bump to latest revm version
Closes #875

bump to revm 5.0.0

---

.github/workflows/book.yaml
.github/workflows/test.yaml
.gitignore
Cargo.toml
docs/Cargo.lock
docs/Cargo.toml
docs/src/usage/arbiter_core/environment.md

fix: release-plz

---

.github/workflows/test.yaml
.gitmodules
Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/console/mod.rs
core/src/database/inspector.rs
core/src/database/mod.rs
core/src/environment/mod.rs
core/src/lib.rs
docs/src/usage/arbiter_core/environment.md
docs/src/usage/arbiter_core/middleware.md
engine/src/agent.rs

chore: remove submodule
chore: rm --cached examples/template
chore: bump dependancies
Affirmation: Your pipeline is green 💚
https://www.youtube.com/watch?v=ia8Q51ouA_s

Some repository Tender Loving Care. Should fix release please once merged. 

---

examples/leader/src/lib.rs

Fix height and width not being used

Use height and width passed in to canvas to limit where leaders can go
